name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install logisim
      run: |
        sudo apt install logisim
    - name: Run test
      run: |
        conda install flake8
        python3 ./test.py tests s-mips.circ -o ./tests-out -t s-mips-template.circ
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
